name: Run Reports

on:
  workflow_dispatch:
  schedule:
    - cron: "50 9,17,1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Gather stats script
        shell: pwsh
        run: |
          import-module ./PSToolKit/Public/Get-MyPSGalleryStat.ps1
          Get-MyPSGalleryStat -GitHubUserID ${{secrets.GITHUB_USER}} -GitHubToken ${{secrets.GITHUB_TOKEN}}