name: Run PSGallery Reports

on:
  workflow_dispatch:
  schedule:
    - cron: "50 9,17,1 * * *"
jobs:
  RunPWSH:
    runs-on: ubuntu-latest
    steps:
     - name: Import Functions
        shell: pwsh
        run: ./run.ps1
      - name: Run Gather stats script
        shell: pwsh
        run: Get-MyPSGalleryStat -GitHubUserID ${{secrets.GH_USER}} -GitHubToken ${{secrets.GH_TOKEN}}