name: Run PSGallery Reports

on:
  workflow_dispatch:
  schedule:
    - cron: "50 9,17,1 * * *"
jobs:
  RunPWSH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Gather stats script
        shell: pwsh
        run: |
          import-module ./PSToolKit/Public/Get-MyPSGalleryStat.ps1 -Force -Global
          import-module ./PSToolKit/Public/Write-Message.ps1 -Force -Global
          Get-MyPSGalleryStat -GitHubUserID ${{secrets.GH_USER}} -GitHubToken ${{secrets.GH_TOKEN}}
